### ISSUE TITLE
Monitoring - sub distorted output

### ISSUE THREAD

**Issue by vcvrackideas** [n0jo/rackwindows#9]
Hi Jens! Sub is very cool feature in the monitoring module to check low end in the mix. But it produces distorted sound when RMS (according to MM mixer) go over -12db. Can you increase a value of clipping just for this mode? Other mode work awesome though without any distortion

**Comment by n0jo** [comment]
Well, part of the idea of these Airwindows ports is to honor the original vision and _not_ meddle with the algorithms themselves (unless something is seriously broken, which I believe is not the case here). This is what Chris himself said about Subs and the loudness issue.

> It’s okay if SubsOnly is louder for fullbodied bass: with that, it’s not so much about level-matching, it’s about getting your sound (at whatever desired loudness) and then having the bass still make sense through SubsOnly. If you’re madly overloading it, there won’t be groove, just a lot of thunder and noise, at elevated levels.

That said, I'll look into it for sure, because it probably shouldn't distort at those levels.

**Comment by n0jo** [comment]
After a quick check I'm fairly sure the module doesn't distort internally, but the raised output volume of the Subs mode causes Audio-8 to clip. Since Monitoring is meant to be placed last in the chain I'll adjust the working gain for Subs and also Peaks, so these modes will hopefully not be able to exceed the unprocessed signal's level anymore.

**Comment by vcvrackideas** [comment]
> After a quick check I'm fairly sure the module doesn't distort internally, but the raised output volume of the Subs mode causes Audio-8 to clip. Since Monitoring is meant to be placed last in the chain I'll adjust the working gain for Subs and also Peaks, so these modes will hopefully not be able to exceed the unprocessed signal's level anymore.

Thank for checking it Jens! Looking forward to the update!

**Comment by airwindows** [comment]
Bear in mind if you do that it's not Monitoring anymore. The levels are part of how those work: they're calibrated so that if you do get excessive sound and clipping, it means that there is an element in your mix that is excessive.

To change that is much like taking a clip meter, and changing the value going into it so there's still a problem but the meter doesn't light. I can only assume people are trying to put out unrealistic mixes directly from their modular systems… which is SUPER normal and understandable. I get that people would run into this problem.

But bottom line is, it is not Monitoring if Subs and Peak let you frame a mix that peaks louder than -12 RMS DB, because you should not be making any sort of mix with RMS louder than -12 dB. -18 is probably better still, but that would be the plugin Righteous. If you peak louder than -12 RMS, streaming platforms will turn you down anyway: you should control the output of your synth better if you're treating it as final mix output. There's always SubsOnly (same thing) if you want to make a module that can produce that sound specifically as a tone effect: Monitoring is not that. If you break the gain staging it will not function as a mix check anymore, and you will be redesigning it to make people push greatly elevated bass through their systems to get their results, and it will fail on correctly balanced mixes.

If you do break it can you specify a version that runs as intended so I can use it when I do Rack stuff? :)

**Comment by n0jo** [comment]
Thanks for chiming in, Chris. I hear you, that's why I was hesitant to make changes in the first place. I didn't know though, that clipping is actually part of the equation to indicate one has taken things too far. Always thought of it more as a tool to gauge the characteristics of a signal, not so much the levels. You live and learn. In this case, I have no intention to change the default behaviour at all. Even as an option it doesn't make sense, considering what you just said.

As a side note, I don't think many people are using Rack as a mixing platform though (yet). Which could change I guess, not least due the drivable Console system in combination with MixMaster :-p If you get the chance to check that out too, I'd love to hear your thoughts (maybe via email, not in this issue).

Cheers

**Comment by vcvrackideas** [comment]
Just checked your develop branch - issue was been fixed! Thank you very much!
